export const productData = [
  {
    "id": 1,
    "imageUrl": "/products/apples.jpg",
    "altText": "Organic red and green apples in a basket",
    "title": "Organic Apples (1kg)",
    "description": "Fresh, crisp, and juicy organic apples. Perfect for a healthy snack or baking.",
    "price": 55.99,
    "rating": 4.8,
    "category": "Food Pantry",
  },
  {
    "id": 2,
    "imageUrl": "/products/bananas.jpg",
    "altText": "Bunch of ripe yellow organic bananas",
    "title": "Organic Bananas (Bunch)",
    "description": "Naturally sweet and creamy organic bananas. A great source of potassium and energy.",
    "price": 52.49,
    "rating": 4.5,
    "category": "Food Pantry",
  },
  {
    "id": 3,
    "imageUrl": "/products/blueberries.jpg",
    "altText": "Small container of fresh organic blueberries",
    "title": "Organic Blueberries (125g)",
    "description": "Packed with antioxidants, these organic blueberries are perfect for smoothies, yogurt, or cereal.",
    "price": 43.99,
    "rating": 4.9,
    "category": "Food Pantry",
  },
  {
    "id": 4,
    "imageUrl": "/products/broccoli.jpg",
    "altText": "Organic broccoli florets with long green stalks",
    "title": "Organic Broccoli (Head)",
    "description": "Fresh and flavorful organic broccoli. A healthy and versatile vegetable.",
    "price": 52.99,
    "rating": 4.7,
    "category": ["Food Pantry", "Plants & Herbs"],
  },
  {
    "id": 5,
    "imageUrl": "/products/carrots.jpg",
    "altText": "Bunch of fresh orange organic carrots with green tops",
    "title": "Organic Carrots (Bunch)",
    "description": "Crisp, sweet, and nutritious organic carrots. Great for snacking or roasting.",
    "price": 31.79,
    "rating": 4.3,
    "category": "Food Pantry",
  },
  {
    "id": 6,
    "imageUrl": "/products/celery.jpg",
    "altText": "Head of organic celery with long green stalks and leaves",
    "title": "Organic Celery (Head)",
    "description": "Fresh and crunchy organic celery. A delicious and healthy addition to salads or snacks.",
    "price": 21.99,
    "rating": 4.1,
    "category": "Food Pantry",
  },
  {
    "id": 7,
    "imageUrl": "/products/coffee-beans.jpg",
    "altText": "Bag of roasted organic fair trade coffee beans",
    "title": "Organic Fair Trade Coffee (250g)",
    "description": "Rich and flavorful organic coffee beans, supporting sustainable farming practices.",
    "price": 67.99,
    "rating": 4.7,
    "category": "Food Pantry",
  },
  {
    "id": 8,
    "imageUrl": "/products/flax-seeds.jpg",
    "altText": "Small bag of golden organic flax seeds",
    "title": "Organic Flax Seeds (200g)",
    "description": "A great source of fiber and omega-3 fatty acids. Enjoy them sprinkled on cereal, yogurt, or smoothies.",
    "price": 35.49,
    "rating": 4.2,
    "category": ["Plants & Herbs", "Food Pantry"],
  },
  {
    "id": 9,
    "imageUrl": "/products/garlic.jpg",
    "altText": "Bunch of fresh organic garlic bulbs",
    "title": "Organic Garlic (Head)",
    "description": "Fresh and pungent organic garlic. Essential for adding flavor to your cooking.",
    "price": 41.29,
    "rating": 4.4,
    "category": ["Food Pantry", "Plants & Herbs"],
  },
  {
    "id": 10,
    "imageUrl": "/products/ginger.jpg",
    "altText": "Organic ginger root with bumpy brown skin",
    "title": "Organic Ginger Root",
    "description": "Fresh and aromatic",
    "price": 41.29,
    "rating": 4.4,
    "category": ["Food Pantry", "Plants & Herbs"],
  },
  {
    "id": 11,
    "imageUrl": "/products/basil.jpg",
    "altText": "Fresh organic basil leaves",
    "title": "Organic Basil (30g)",
    "description": "Aromatic and flavorful, perfect for pesto, salads, and marinades.",
    "price": 29.99,
    "rating": 4.8,
    "category": "Plants & Herbs"
  },
  {
    "id": 12,
    "imageUrl": "/products/cilantro.jpg",
    "altText": "Fresh organic cilantro bunch",
    "title": "Organic Cilantro (30g)",
    "description": "Bright and zesty, ideal for tacos, salsas, and garnishes.",
    "price": 25.99,
    "rating": 4.6,
    "category": "Plants & Herbs"
  },
  {
    "id": 13,
    "imageUrl": "/products/parsley.jpg",
    "altText": "Fresh organic parsley bunch",
    "title": "Organic Parsley (30g)",
    "description": "Fresh and vibrant, great for garnishing and flavoring dishes.",
    "price": 19.99,
    "rating": 4.5,
    "category": "Plants & Herbs"
  },
  {
    "id": 14,
    "imageUrl": "/products/thyme.jpg",
    "altText": "Dried organic thyme leaves",
    "title": "Organic Thyme (15g)",
    "description": "Fragrant dried thyme, perfect for soups, stews, and roasted meats.",
    "price": 22.99,
    "rating": 4.7,
    "category": "Plants & Herbs"
  },
  {
    "id": 15,
    "imageUrl": "/products/rosemary.jpg",
    "altText": "Fresh organic rosemary sprigs",
    "title": "Organic Rosemary (30g)",
    "description": "Earthy and aromatic, a great addition to roasted vegetables and meats.",
    "price": 27.99,
    "rating": 4.6,
    "category": "Plants & Herbs"
  },
  {
    "id": 16,
    "imageUrl": "/products/sage.jpg",
    "altText": "Fresh organic sage leaves",
    "title": "Organic Sage (30g)",
    "description": "Savory and aromatic, perfect for stuffing and hearty dishes.",
    "price": 24.99,
    "rating": 4.8,
    "category": "Plants & Herbs"
  },
  {
    "id": 17,
    "imageUrl": "/products/mint.jpg",
    "altText": "Fresh organic mint leaves",
    "title": "Organic Mint (30g)",
    "description": "Refreshing and fragrant, perfect for teas, desserts, and salads.",
    "price": 21.99,
    "rating": 4.9,
    "category": "Plants & Herbs"
  },
  {
    "id": 18,
    "imageUrl": "/products/dill.jpg",
    "altText": "Fresh organic dill sprigs",
    "title": "Organic Dill (30g)",
    "description": "Fragrant dill, great for pickling, salads, and seafood dishes.",
    "price": 20.99,
    "rating": 4.5,
    "category": "Plants & Herbs"
  },
  {
    "id": 19,
    "imageUrl": "/products/chives.jpg",
    "altText": "Fresh organic chives",
    "title": "Organic Chives (30g)",
    "description": "Delicate onion flavor, perfect for garnishing soups and salads.",
    "price": 18.99,
    "rating": 4.7,
    "category": "Plants & Herbs"
  },
  {
    "id": 20,
    "imageUrl": "/products/tarragon.jpg",
    "altText": "Dried organic tarragon leaves",
    "title": "Organic Tarragon (15g)",
    "description": "Anise-flavored herb, excellent for dressings and French cuisine.",
    "price": 23.99,
    "rating": 4.6,
    "category": "Plants & Herbs"
  },
  {
    "id": 21,
    "imageUrl": "/products/oregano.jpg",
    "altText": "Dried organic oregano leaves",
    "title": "Organic Oregano (15g)",
    "description": "Robust and flavorful, perfect for Italian dishes and pizza.",
    "price": 19.99,
    "rating": 4.8,
    "category": "Plants & Herbs"
},
  {
    "id": 22,
    "imageUrl": "/products/bay_leaves.jpg",
    "imageUrl": "/products/lemongrass.jpg",
    "altText": "Fresh organic lemongrass stalks",
    "title": "Organic Lemongrass (30g)",
    "description": "Citrusy and fragrant, ideal for soups, teas, and stir-fries.",
    "price": 26.99,
    "rating": 4.7,
    "category": "Plants & Herbs"
  },
  {
    "id": 23,
    "imageUrl": "/products/green_onion.jpg",
    "altText": "Fresh organic green onions",
    "title": "Organic Green Onions (30g)",
    "description": "Mild onion flavor, perfect for salads, soups, and garnishes.",
    "price": 15.99,
    "rating": 4.9,
    "category": "Plants & Herbs"
  },
  {
    "id": 24,
    "imageUrl": "/products/rosemary_salt.jpg",
    "altText": "Organic rosemary salt blend",
    "title": "Organic Rosemary Salt (100g)",
    "description": "A blend of sea salt and organic rosemary for seasoning meats and vegetables.",
    "price": 32.99,
    "rating": 4.6,
    "category": "Plants & Herbs"
  },
  {
    "id": 25,
    "imageUrl": "/products/sweet_paprika.jpg",
    "altText": "Dried sweet paprika powder",
    "title": "Organic Sweet Paprika (50g)",
    "description": "Rich and flavorful spice, great for seasoning and color.",
    "price": 17.99,
    "rating": 4.8,
    "category": "Plants & Herbs"
  },
  {
    "id": 26,
    "imageUrl": "/products/saffron.jpg",
    "altText": "Organic saffron threads",
    "title": "Organic Saffron (1g)",
    "description": "Luxurious and aromatic saffron threads, perfect for paella and risottos.",
    "price": 199.99,
    "rating": 4.9,
    "category": "Plants & Herbs"
  },
  {
    "id": 27,
    "imageUrl": "/products/cardamom.jpg",
    "altText": "Dried organic cardamom pods",
    "title": "Organic Cardamom (30g)",
    "description": "Warm and aromatic spice, great for desserts and chai tea.",
    "price": 34.99,
    "rating": 4.7,
    "category": "Plants & Herbs"
  },
  {
    "id": 28,
    "imageUrl": "/products/ginger.jpg",
    "altText": "Fresh organic ginger root",
    "title": "Organic Ginger (100g)",
    "description": "Spicy and zesty, perfect for teas, stir-fries, and baking.",
    "price": 27.99,
    "rating": 4.8,
    "category": "Plants & Herbs"
  },
  {
    "id": 29,
    "imageUrl": "/products/wasabi.jpg",
    "altText": "Fresh organic wasabi root",
    "title": "Organic Wasabi (50g)",
    "description": "Spicy and pungent, perfect for sushi and dressings.",
    "price": 39.99,
    "rating": 4.9,
    "category": "Plants & Herbs"
  },
  {
    "id": 30,
    "imageUrl": "/products/fennel.jpg",
    "altText": "Fresh organic fennel bulb",
    "title": "Organic Fennel (1 bulb)",
    "description": "Sweet and anise-flavored, great for salads and roasting.",
    "price": 24.99,
    "rating": 4.5,
    "category": "Plants & Herbs"
  },
  {
    "id": 31,
    "imageUrl": "/products/horseradish.jpg",
    "altText": "Fresh organic horseradish root",
    "title": "Organic Horseradish (100g)",
    "description": "Spicy and pungent, perfect for sauces and condiments.",
    "price": 29.99,
    "rating": 4.6,
    "category": "Plants & Herbs"
  },
  {
    "id": 32,
    "imageUrl": "/products/seaweed.jpg",
    "altText": "Dried organic seaweed sheets",
    "title": "Organic Seaweed (50g)",
    "description": "Nutritious and flavorful, perfect for sushi and salads.",
    "price": 18.99,
    "rating": 4.7,
    "category": "Plants & Herbs"
  },
  {
    "id": 33,
    "imageUrl": "/products/pepper.jpg",
    "altText": "Dried organic black peppercorns",
    "title": "Organic Black Pepper (50g)",
    "description": "Bold and pungent, essential for seasoning and cooking.",
    "price": 15.99,
    "rating": 4.8,
    "category": "Plants & Herbs"
  },
  {
    "id": 34,
    "imageUrl": "/products/garlic.jpg",
    "altText": "Fresh organic garlic bulbs",
    "title": "Organic Garlic (3 bulbs)",
    "description": "Pungent and flavorful, great for seasoning and cooking.",
    "price": 19.99,
    "rating": 4.9,
    "category": ["Plants & Herbs", "Food Pantry"]
  },
  {
    "id": 35,
    "imageUrl": "/products/rose_water.jpg",
    "altText": "Bottle of organic rose water",
    "title": "Organic Rose Water (200ml)",
    "description": "Hydrating and soothing, perfect for toning and refreshing the skin.",
    "price": 29.99,
    "rating": 4.8,
    "category": "Skin & Beauty"
},
{

    "imageUrl": "/products/coconut_oil.jpg",
    "altText": "Jar of organic coconut oil",
    "title": "Organic Coconut Oil (250ml)",
    "description": "Moisturizing and versatile, ideal for skin, hair, and cooking.",
    "price": 34.99,
    "rating": 4.9,
    "category": "Skin & Beauty"
},
{
  "id": 37,
    "imageUrl": "/products/aloe_vera_gel.jpg",
    "altText": "Tube of organic aloe vera gel",
    "title": "Organic Aloe Vera Gel (150ml)",
    "description": "Soothing and hydrating, perfect for after-sun care and moisturizing.",
    "price": 19.99,
    "rating": 4.7,
    "category": "Skin & Beauty"
},
{
  "id": 38,
    "imageUrl": "/products/argan_oil.jpg",
    "altText": "Bottle of organic argan oil",
    "title": "Organic Argan Oil (100ml)",
    "description": "Rich in antioxidants, ideal for nourishing skin and hair.",
    "price": 42.99,
    "rating": 4.8,
    "category": "Skin & Beauty"
},
{
  "id": 39,
    "imageUrl": "/products/jojoba_oil.jpg",
    "altText": "Bottle of organic jojoba oil",
    "title": "Organic Jojoba Oil (100ml)",
    "description": "Moisturizing and non-comedogenic, perfect for all skin types.",
    "price": 25.99,
    "rating": 4.6,
    "category": "Skin & Beauty"
},
{
  "id": 40,
    "imageUrl": "/products/shea_butter.jpg",
    "altText": "Jar of organic shea butter",
    "title": "Organic Shea Butter (200g)",
    "description": "Ultra-hydrating and nourishing, ideal for dry skin and hair.",
    "price": 34.99,
    "rating": 4.9,
    "category": "Skin & Beauty"
},
{
  "id": 41,
    "imageUrl": "/products/lavender_oil.jpg",
    "altText": "Bottle of organic lavender essential oil",
    "title": "Organic Lavender Oil (15ml)",
    "description": "Calming and aromatic, perfect for relaxation and skincare.",
    "price": 19.99,
    "rating": 4.7,
    "category": "Skin & Beauty"
},
{
  "id": 42,
    "imageUrl": "/products/tea_tree_oil.jpg",
    "altText": "Bottle of organic tea tree oil",
    "title": "Organic Tea Tree Oil (15ml)",
    "description": "Antibacterial and soothing, great for acne-prone skin.",
    "price": 22.99,
    "rating": 4.8,
    "category": "Skin & Beauty"
},
{
  "id": 43,
    "imageUrl": "/products/charcoal_mask.jpg",
    "altText": "Tube of organic charcoal face mask",
    "title": "Organic Charcoal Face Mask (100ml)",
    "description": "Purifying and detoxifying, ideal for oily and congested skin.",
    "price": 28.99,
    "rating": 4.6,
    "category": "Skin & Beauty"
},
{
  "id": 44,
    "imageUrl": "/products/exfoliating_scrub.jpg",
    "altText": "Jar of organic exfoliating scrub",
    "title": "Organic Exfoliating Scrub (150g)",
    "description": "Gently removes dead skin cells for a smooth, radiant complexion.",
    "price": 26.99,
    "rating": 4.7,
    "category": "Skin & Beauty"
},
{
  "id": 45,
    "imageUrl": "/products/natural_soap.jpg",
    "altText": "Bar of organic natural soap",
    "title": "Organic Natural Soap (100g)",
    "description": "Gentle and moisturizing, made with natural ingredients.",
    "price": 14.99,
    "rating": 4.9,
    "category": "Skin & Beauty"
},
{
  "id": 46,
    "imageUrl": "/products/sunscreen.jpg",
    "altText": "Bottle of organic sunscreen",
    "title": "Organic Sunscreen SPF 30 (150ml)",
    "description": "Protects skin from harmful UV rays while moisturizing.",
    "price": 32.99,
    "rating": 4.8,
    "category": "Skin & Beauty"
},
{
  "id": 47,
    "imageUrl": "/products/facial_serum.jpg",
    "altText": "Bottle of organic facial serum",
    "title": "Organic Facial Serum (30ml)",
    "description": "Nourishing serum for brighter, more youthful skin.",
    "price": 49.99,
    "rating": 4.9,
    "category": "Skin & Beauty"
},
{
  "id": 48,
    "imageUrl": "/products/eye_cream.jpg",
    "altText": "Jar of organic eye cream",
    "title": "Organic Eye Cream (15ml)",
    "description": "Hydrating and firming, reduces the appearance of dark circles.",
    "price": 39.99,
    "rating": 4.7,
    "category": "Skin & Beauty"
},
{
  "id": 49,
    "imageUrl": "/products/moisturizer.jpg",
    "altText": "Jar of organic moisturizer",
    "title": "Organic Face Moisturizer (50ml)",
    "description": "Lightweight and hydrating, suitable for daily use.",
    "price": 34.99,
    "rating": 4.8,
    "category": "Skin & Beauty"
},
{
  "id": 50,
    "imageUrl": "/products/body_lotion.jpg",
    "altText": "Bottle of organic body lotion",
    "title": "Organic Body Lotion (250ml)",
    "description": "Luxuriously hydrating, keeps skin soft and smooth all day.",
    "price": 29.99,
    "rating": 4.6,
    "category": "Skin & Beauty"
},
{
  "id": 51,
    "imageUrl": "/products/lip_balm.jpg",
    "altText": "Tube of organic lip balm",
    "title": "Organic Lip Balm (15g)",
    "description": "Moisturizing and protective, perfect for chapped lips.",
    "price": 9.99,
    "rating": 4.9,
    "category": "Skin & Beauty"
},
{
  "id": 52,
    "imageUrl": "/products/face_mask.jpg",
    "altText": "Sheet mask pack",
    "title": "Organic Face Mask Pack (5 sheets)",
    "description": "Hydrating and revitalizing masks for a glowing complexion.",
    "price": 25.99,
    "rating": 4.7,
    "category": "Skin & Beauty"
},
{
  "id": 53,
    "imageUrl": "/products/whitening_toothpaste.jpg",
    "altText": "Tube of organic whitening toothpaste",
    "title": "Organic Whitening Toothpaste (100g)",
    "description": "Gentle and effective, promotes whiter teeth and fresh breath.",
    "price": 14.99,
    "rating": 4.8,
    "category": "Skin & Beauty"
},
{
  "id": 54,
  "imageUrl": "/products/almond_butter.jpg",
  "altText": "Jar of organic almond butter",
  "title": "Organic Almond Butter (250g)",
  "description": "Creamy and delicious, perfect for spreading or adding to smoothies.",
  "price": 39.99,
  "rating": 4.8,
  "category": "Snacks & Drinks"
},
{
  "id": 55,
  "imageUrl": "/products/chia_seeds.jpg",
  "altText": "Pack of organic chia seeds",
  "title": "Organic Chia Seeds (200g)",
  "description": "Nutritious and versatile, great for smoothies, puddings, and baking.",
  "price": 18.99,
  "rating": 4.7,
  "category": "Snacks & Drinks"
},
{
  "id": 56,
  "imageUrl": "/products/dark_chocolate.jpg",
  "altText": "Bar of organic dark chocolate",
  "title": "Organic Dark Chocolate (100g)",
  "description": "Rich and indulgent, perfect for a sweet treat.",
  "price": 24.99,
  "rating": 4.9,
  "category": "Snacks & Drinks"
},
{
  "id": 57,
  "imageUrl": "/products/popcorn.jpg",
  "altText": "Bag of organic popcorn",
  "title": "Organic Popcorn (150g)",
  "description": "Light and crunchy, perfect for snacking or movie nights.",
  "price": 14.99,
  "rating": 4.8,
  "category": "Snacks & Drinks"
},
{
  "id": 58,
  "imageUrl": "/products/fruit_leather.jpg",
  "altText": "Pack of organic fruit leather",
  "title": "Organic Fruit Leather (5 pieces)",
  "description": "Naturally sweet and chewy, a healthy snack for on-the-go.",
  "price": 19.99,
  "rating": 4.7,
  "category": "Snacks & Drinks"
},
{
  "id": 59,
  "imageUrl": "/products/energy_bars.jpg",
  "altText": "Box of organic energy bars",
  "title": "Organic Energy Bars (10 bars)",
  "description": "Nutritious and filling, perfect for a quick snack or post-workout.",
  "price": 34.99,
  "rating": 4.8,
  "category": "Snacks & Drinks"
},
{
  "id": 60,
  "imageUrl": "/products/tea.jpg",
  "altText": "Box of organic herbal tea",
  "title": "Organic Herbal Tea (20 bags)",
  "description": "Relaxing and flavorful, great for unwinding any time of day.",
  "price": 12.99,
  "rating": 4.9,
  "category": "Snacks & Drinks"
},
{
  "id": 61,
  "imageUrl": "/products/coffee.jpg",
  "altText": "Bag of organic coffee beans",
  "title": "Organic Coffee Beans (250g)",
  "description": "Rich and aromatic, perfect for a morning boost.",
  "price": 29.99,
  "rating": 4.8,
  "category": "Snacks & Drinks"
},
{
  "id": 62,
  "imageUrl": "/products/fruit_nuts_mix.jpg",
  "altText": "Pack of organic fruit and nut mix",
  "title": "Organic Fruit & Nut Mix (200g)",
  "description": "Healthy and satisfying, perfect for snacking any time.",
  "price": 22.99,
  "rating": 4.6,
  "category": "Snacks & Drinks"
},
{
  "id": 63,
  "imageUrl": "/products/smoothie_mixture.jpg",
  "altText": "Pack of organic smoothie mixture",
  "title": "Organic Smoothie Mix (300g)",
  "description": "Blend of fruits and superfoods, ideal for quick and nutritious smoothies.",
  "price": 27.99,
  "rating": 4.7,
  "category": "Snacks & Drinks"
},
{
  "id": 64,
  "imageUrl": "/products/hummus.jpg",
  "altText": "Container of organic hummus",
  "title": "Organic Hummus (250g)",
  "description": "Creamy and flavorful, perfect for dipping veggies or spreading.",
  "price": 14.99,
  "rating": 4.8,
  "category": "Snacks & Drinks"
},
{
  "id": 65,
  "imageUrl": "/products/jerky.jpg",
  "altText": "Pack of organic beef jerky",
  "title": "Organic Beef Jerky (100g)",
  "description": "Savory and protein-packed, great for a hearty snack.",
  "price": 29.99,
  "rating": 4.6,
  "category": "Snacks & Drinks"
},
{
  "id": 66,
  "imageUrl": "/products/salsa.jpg",
  "altText": "Jar of organic salsa",
  "title": "Organic Salsa (300g)",
  "description": "Fresh and zesty, perfect for chips or topping dishes.",
  "price": 12.99,
  "rating": 4.7,
  "category": "Snacks & Drinks"
},
{
  "id": 67,
  "imageUrl": "/products/nut_butter.jpg",
  "altText": "Jar of organic peanut butter",
  "title": "Organic Peanut Butter (250g)",
  "description": "Creamy and rich, ideal for spreads, smoothies, and baking.",
  "price": 19.99,
  "rating": 4.8,
  "category": "Snacks & Drinks"
},
{
  "id": 68,
  "imageUrl": "/products/protein_powder.jpg",
  "altText": "Tub of organic protein powder",
  "title": "Organic Protein Powder (500g)",
  "description": "Ideal for shakes and smoothies, packed with nutrients.",
  "price": 39.99,
  "rating": 4.9,
  "category": "Snacks & Drinks"
},
{
  "id": 69,
  "imageUrl": "/products/coconut_water.jpg",
  "altText": "Carton of organic coconut water",
  "title": "Organic Coconut Water (1L)",
  "description": "Hydrating and refreshing, perfect for post-workout recovery.",
  "price": 14.99,
  "rating": 4.7,
  "category": "Snacks & Drinks"
},
{
  "id": 70,
  "imageUrl": "/products/sparkling_water.jpg",
  "altText": "Bottle of organic sparkling water",
  "title": "Organic Sparkling Water (500ml)",
  "description": "Refreshing and bubbly, a great alternative to sugary drinks.",
  "price": 2.99,
  "rating": 4.6,
  "category": "Snacks & Drinks"
},
{
  "id": 71,
  "imageUrl": "/products/fruit_juice.jpg",
  "altText": "Bottle of organic fruit juice",
  "title": "Organic Fruit Juice (1L)",
  "description": "Refreshing and naturally sweet, made from real fruits.",
  "price": 10.99,
  "rating": 4.8,
  "category": "Snacks & Drinks"
},
{
  "id": 72,
  "imageUrl": "/products/protein_bars.jpg",
  "altText": "Box of organic protein bars",
  "title": "Organic Protein Bars (12 bars)",
  "description": "Nutritious and convenient, ideal for on-the-go energy.",
  "price": 34.99,
  "rating": 4.9,
  "category": "Snacks & Drinks"
},
{
  "id": 73,
  "imageUrl": "/products/spirulina.jpg",
  "altText": "Pack of organic spirulina powder",
  "title": "Organic Spirulina Powder (200g)",
  "description": "Nutrient-dense blue-green algae, great for smoothies and health drinks.",
  "price": 34.99,
  "rating": 4.8,
  "category": "Super Foods"
},
{
  "id": 74,
  "imageUrl": "/products/maca.jpg",
  "altText": "Pack of organic maca powder",
  "title": "Organic Maca Powder (200g)",
  "description": "Natural energy booster, ideal for smoothies and baking.",
  "price": 29.99,
  "rating": 4.7,
  "category": "Super Foods"
},
{
  "id": 75,
  "imageUrl": "/products/baobab.jpg",
  "altText": "Pack of organic baobab powder",
  "title": "Organic Baobab Powder (150g)",
  "description": "Rich in vitamin C and antioxidants, perfect for smoothies and yogurt.",
  "price": 24.99,
  "rating": 4.9,
  "category": "Super Foods"
},
{
  "id": 76,
  "imageUrl": "/products/chia_seeds.jpg",
  "altText": "Pack of organic chia seeds",
  "title": "Organic Chia Seeds (200g)",
  "description": "High in omega-3s and fiber, great for puddings and smoothies.",
  "price": 18.99,
  "rating": 4.8,
  "category": "Super Foods"
},
{
  "id": 77,
  "imageUrl": "/products/hemp_seeds.jpg",
  "altText": "Pack of organic hemp seeds",
  "title": "Organic Hemp Seeds (200g)",
  "description": "Rich in protein and essential fatty acids, perfect for salads and smoothies.",
  "price": 22.99,
  "rating": 4.7,
  "category": "Super Foods"
},
{
  "id": 78,
  "imageUrl": "/products/goji_berries.jpg",
  "altText": "Pack of organic goji berries",
  "title": "Organic Goji Berries (150g)",
  "description": "Sweet and nutrient-packed, great for snacking and adding to dishes.",
  "price": 29.99,
  "rating": 4.8,
  "category": "Super Foods"
},
{
  "id": 79,
  "imageUrl": "/products/turmeric.jpg",
  "altText": "Pack of organic turmeric powder",
  "title": "Organic Turmeric Powder (100g)",
  "description": "Anti-inflammatory spice, ideal for curries, teas, and health drinks.",
  "price": 19.99,
  "rating": 4.6,
  "category": "Super Foods"
},
{
  "id": 80,
  "imageUrl": "/products/green_tea.jpg",
  "altText": "Pack of organic green tea leaves",
  "title": "Organic Green Tea (50g)",
  "description": "Rich in antioxidants, perfect for a refreshing drink.",
  "price": 14.99,
  "rating": 4.9,
  "category": "Super Foods"
},
{
  "id": 81,
  "imageUrl": "/products/seaweed.jpg",
  "altText": "Pack of organic seaweed snacks",
  "title": "Organic Seaweed Snacks (30g)",
  "description": "Crispy and savory, a nutritious snack rich in minerals.",
  "price": 5.99,
  "rating": 4.7,
  "category": "Super Foods"
},
{
  "id": 82,
  "imageUrl": "/products/linseeds.jpg",
  "altText": "Pack of organic flaxseeds",
  "title": "Organic Flaxseeds (200g)",
  "description": "High in omega-3 fatty acids and fiber, perfect for smoothies and baking.",
  "price": 16.99,
  "rating": 4.6,
  "category": "Super Foods"
},
{
  "id": 83,
  "imageUrl": "/products/cacao_powder.jpg",
  "altText": "Pack of organic cacao powder",
  "title": "Organic Cacao Powder (200g)",
  "description": "Rich in antioxidants, perfect for smoothies and baking.",
  "price": 22.99,
  "rating": 4.8,
  "category": "Super Foods"
},
{
  "id": 84,
  "imageUrl": "/products/quinoa.jpg",
  "altText": "Pack of organic quinoa",
  "title": "Organic Quinoa (500g)",
  "description": "High-protein grain, great for salads, bowls, and sides.",
  "price": 28.99,
  "rating": 4.7,
  "category": "Super Foods"
},
{
  "id": 85,
  "imageUrl": "/products/elderberry.jpg",
  "altText": "Pack of organic elderberry syrup",
  "title": "Organic Elderberry Syrup (250ml)",
  "description": "Immune-boosting syrup, perfect for wellness shots.",
  "price": 34.99,
  "rating": 4.9,
  "category": "Super Foods"
},
{
  "id": 86,
  "imageUrl": "/products/matcha.jpg",
  "altText": "Pack of organic matcha powder",
  "title": "Organic Matcha Powder (100g)",
  "description": "Premium green tea powder, perfect for lattes and smoothies.",
  "price": 39.99,
  "rating": 4.8,
  "category": "Super Foods"
},
{
  "id": 87,
  "imageUrl": "/products/spirulina_tablets.jpg",
  "altText": "Bottle of organic spirulina tablets",
  "title": "Organic Spirulina Tablets (200 tablets)",
  "description": "Convenient source of nutrients, ideal for on-the-go health.",
  "price": 29.99,
  "rating": 4.7,
  "category": "Super Foods"
},
{
  "id": 88,
  "imageUrl": "/products/moringa.jpg",
  "altText": "Pack of organic moringa powder",
  "title": "Organic Moringa Powder (150g)",
  "description": "Nutrient-dense powder, great for smoothies and health drinks.",
  "price": 24.99,
  "rating": 4.9,
  "category": "Super Foods"
},
{
  "id": 89,
  "imageUrl": "/products/superfood_blend.jpg",
  "altText": "Pack of organic superfood blend",
  "title": "Organic Superfood Blend (250g)",
  "description": "A mix of nutrient-rich superfoods for smoothies and bowls.",
  "price": 34.99,
  "rating": 4.8,
  "category": "Super Foods"
},
{
  "id": 90,
  "imageUrl": "/products/nutritional_yeast.jpg",
  "altText": "Pack of organic nutritional yeast",
  "title": "Organic Nutritional Yeast (200g)",
  "description": "Cheesy flavor, perfect for seasoning and adding nutrients.",
  "price": 19.99,
  "rating": 4.6,
  "category": "Super Foods"
},
{ "id": 91, 
  "imageUrl": "https://images.unsplash.com/photo-1542282910-7337bcfea235?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTh8fG9yZ2FuaWMlMjBkcmlua3N8ZW58MHx8MHx8fDA%3D",
  "altText": "Royal Red Berry",
  "title": "Royal Red Berry",
  "description": "Red berry juice with a hint of mint",
  "price": 38,
  "rating": 4.7,
  "category": "Snacks & Drinks",
  "variant": "deluxe"
},
{ "id": 92, 
  "imageUrl": "https://images.unsplash.com/photo-1560526860-1f0e56046c85?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8b3JnYW5pYyUyMGRyaW5rc3xlbnwwfHwwfHx8MA%3D%",
  "altText": "Orange & Cherry mix",
  "title": "Orange & Cherry mix",
  "description": "Orange & Cherry mix with a hint of mint",
  "price": 35,
  "rating": 4.8,
  "category": "Snacks & Drinks",
  "variant": "special"
},
{ "id": 93, 
  "imageUrl": "https://images.unsplash.com/photo-1543648973-1eb94629e7a6?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MzZ8fG9yZ2FuaWMlMjBkcmlua3N8ZW58MHx8MHx8fDA%3D",
  "altText": "Avocado smoothie",
  "title": "Avocado smoothie",
  "description": "Avocado smoothie juice with a hint of mint",
  "price": 35,
  "rating": 4.5,
  "category": "Snacks & Drinks",
  "variant": "special"
},

]
