import { Inter } from "next/font/google"
import "./globals.css"

import Navigation from "../components/navigation"
import Footer from "../components/layout/footer"
import { ThemeProvider } from "../context/ThemeContext"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider >

          <Navigation />

          <main className={`bg-gradient-radial from-green-800 to-green-100 dark:from-green-400 dark:to-black dark:text-green-200 text-green-950`}>{children}</main>
          
          <Footer />

        </ThemeProvider>
      </body>
    </html>
  )
}
